//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNSharp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account &apos;{0}&apos; does not exist.  Attempting to create....
        /// </summary>
        internal static string AccountDNECreating {
            get {
                return ResourceManager.GetString("AccountDNECreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more names of users to invite is null..
        /// </summary>
        internal static string BnetClient_InviteUsersToNewClan_NullUser {
            get {
                return ResourceManager.GetString("BnetClient_InviteUsersToNewClan_NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly 9 users may be invited to form a new clan..
        /// </summary>
        internal static string BnetClient_InviteUsersToNewClan_WrongUserCount {
            get {
                return ResourceManager.GetString("BnetClient_InviteUsersToNewClan_WrongUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan invitation user must not be null or zero-length..
        /// </summary>
        internal static string BnetClient_InviteUserToClan_NullUser {
            get {
                return ResourceManager.GetString("BnetClient_InviteUserToClan_NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &apos;{0}&apos; is not supported with old-style account login..
        /// </summary>
        internal static string BnetClient_LoginAccountOld_ClientNotSupported_fmt {
            get {
                return ResourceManager.GetString("BnetClient_LoginAccountOld_ClientNotSupported_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client must be connected in order to send a message..
        /// </summary>
        internal static string BnetClient_Send_NotConnected {
            get {
                return ResourceManager.GetString("BnetClient_Send_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum text length is 223 characters..
        /// </summary>
        internal static string BnetClient_Send_TooLong {
            get {
                return ResourceManager.GetString("BnetClient_Send_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change the command queue implementation while the client is connected..
        /// </summary>
        internal static string BnetClient_setCommandQueue_Connected {
            get {
                return ResourceManager.GetString("BnetClient_setCommandQueue_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.CdKey1 contained a null or zero-length string..
        /// </summary>
        internal static string BnetClient_Validate_CdKey1Null {
            get {
                return ResourceManager.GetString("BnetClient_Validate_CdKey1Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.CdKey2 contained a null or zero-length string, but the specified product requires two CD keys..
        /// </summary>
        internal static string BnetClient_Validate_CdKey2Null {
            get {
                return ResourceManager.GetString("BnetClient_Validate_CdKey2Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.Client did not specify a client that could connect.  Valid values are STAR, SEXP, D2DV, D2XP, W2BN, WAR3, and W3XP..
        /// </summary>
        internal static string BnetClient_Validate_ClientTypeCantConnect {
            get {
                return ResourceManager.GetString("BnetClient_Validate_ClientTypeCantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.GameExe did not point to a valid file..
        /// </summary>
        internal static string BnetClient_Validate_GameExeDNE {
            get {
                return ResourceManager.GetString("BnetClient_Validate_GameExeDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.GameFile2 did not point to a valid file..
        /// </summary>
        internal static string BnetClient_Validate_GameFile2DNE {
            get {
                return ResourceManager.GetString("BnetClient_Validate_GameFile2DNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.GameFile3 did not point to a valid file..
        /// </summary>
        internal static string BnetClient_Validate_GameFile3DNE {
            get {
                return ResourceManager.GetString("BnetClient_Validate_GameFile3DNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.ImageFile did not point to a valid file, but the selected product uses the Lockdown method of versioning..
        /// </summary>
        internal static string BnetClient_Validate_GameImageFileDNE {
            get {
                return ResourceManager.GetString("BnetClient_Validate_GameImageFileDNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.Client was not valid because it did not specify a valid client type..
        /// </summary>
        internal static string BnetClient_Validate_InvalidClientType {
            get {
                return ResourceManager.GetString("BnetClient_Validate_InvalidClientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.CdKeyOwner was null or zero-length..
        /// </summary>
        internal static string BnetClient_Validate_KeyOwnerNull {
            get {
                return ResourceManager.GetString("BnetClient_Validate_KeyOwnerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.Password was null or zero-length..
        /// </summary>
        internal static string BnetClient_Validate_PasswordNull {
            get {
                return ResourceManager.GetString("BnetClient_Validate_PasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.PingType was not a valid enumeration member for the PingType enumeration..
        /// </summary>
        internal static string BnetClient_Validate_PingTypeInvalid {
            get {
                return ResourceManager.GetString("BnetClient_Validate_PingTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBattleNetSettings.Username was null or zero-length..
        /// </summary>
        internal static string BnetClient_Validate_UsernameNull {
            get {
                return ResourceManager.GetString("BnetClient_Validate_UsernameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a globally-accessible channel.
        /// </summary>
        internal static string ChannelFlags_GloballyAccessibleChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_GloballyAccessibleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a moderated channel.
        /// </summary>
        internal static string ChannelFlags_ModeratedChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_ModeratedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a private channel.
        /// </summary>
        internal static string ChannelFlags_None {
            get {
                return ResourceManager.GetString("ChannelFlags_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a product-specific channel.
        /// </summary>
        internal static string ChannelFlags_ProductSpecificChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_ProductSpecificChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a public channel.
        /// </summary>
        internal static string ChannelFlags_PublicChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_PublicChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a restricted channel.
        /// </summary>
        internal static string ChannelFlags_RestrictedChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_RestrictedChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a silent channel.
        /// </summary>
        internal static string ChannelFlags_SilentChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_SilentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a system channel.
        /// </summary>
        internal static string ChannelFlags_SystemChannel {
            get {
                return ResourceManager.GetString("ChannelFlags_SystemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was unable to complete a connection to {0}:{1} ({2}).  More information is available in the exception..
        /// </summary>
        internal static string ConnectionBase_Connect_ConnectFailed_fmt {
            get {
                return ResourceManager.GetString("ConnectionBase_Connect_ConnectFailed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer was unable to resolve hostname {0}.  If necessary, add an entry to %SystemRoot%\system32\drivers\etc\hosts, or flush your DNS resolver cache, and try again..
        /// </summary>
        internal static string ConnectionBase_Connect_ResolveFailed_fmt {
            get {
                return ResourceManager.GetString("ConnectionBase_Connect_ResolveFailed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net specified an invalid packet size..
        /// </summary>
        internal static string InvalidPacketSizeFromBnet {
            get {
                return ResourceManager.GetString("InvalidPacketSizeFromBnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password..
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server rejected your password..
        /// </summary>
        internal static string LoginProofClientProofFailed {
            get {
                return ResourceManager.GetString("LoginProofClientProofFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server rejected your password with a specific error message: &apos;{0}&apos;.
        /// </summary>
        internal static string LoginProofCustomError {
            get {
                return ResourceManager.GetString("LoginProofCustomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon success!  Battle.net has requested that you register an e-mail address with this account.  You will not be notified again..
        /// </summary>
        internal static string LoginProofRegisterEmail {
            get {
                return ResourceManager.GetString("LoginProofRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was unable to verify that it knew your password; you may be connecting to a malicious server..
        /// </summary>
        internal static string LoginProofServerProofFailed {
            get {
                return ResourceManager.GetString("LoginProofServerProofFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon success!  Entering chat....
        /// </summary>
        internal static string LoginProofSuccess {
            get {
                return ResourceManager.GetString("LoginProofSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too few alphanumeric characters..
        /// </summary>
        internal static string NameCreateFail10 {
            get {
                return ResourceManager.GetString("NameCreateFail10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too many adjacent punctuation characters..
        /// </summary>
        internal static string NameCreateFail11 {
            get {
                return ResourceManager.GetString("NameCreateFail11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained too many punctuation characters..
        /// </summary>
        internal static string NameCreateFail12 {
            get {
                return ResourceManager.GetString("NameCreateFail12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name was too short or blank.  User names should be at least 3 characters long..
        /// </summary>
        internal static string NameCreateFail7 {
            get {
                return ResourceManager.GetString("NameCreateFail7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained one or more illegal characters..
        /// </summary>
        internal static string NameCreateFail8 {
            get {
                return ResourceManager.GetString("NameCreateFail8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name contained one or more illegal words..
        /// </summary>
        internal static string NameCreateFail9 {
            get {
                return ResourceManager.GetString("NameCreateFail9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified user name already exists..
        /// </summary>
        internal static string NameCreateFailOther {
            get {
                return ResourceManager.GetString("NameCreateFailOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created account name &apos;{0}&apos;.  Logging in....
        /// </summary>
        internal static string NameCreateSuccess {
            get {
                return ResourceManager.GetString("NameCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channelName.
        /// </summary>
        internal static string param_channelName {
            get {
                return ResourceManager.GetString("param_channelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clanName.
        /// </summary>
        internal static string param_clanName {
            get {
                return ResourceManager.GetString("param_clanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clanTag.
        /// </summary>
        internal static string param_clanTag {
            get {
                return ResourceManager.GetString("param_clanTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memberToRemove.
        /// </summary>
        internal static string param_memberToRemove {
            get {
                return ResourceManager.GetString("param_memberToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string param_name {
            get {
                return ResourceManager.GetString("param_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newChieftanName.
        /// </summary>
        internal static string param_newChieftanName {
            get {
                return ResourceManager.GetString("param_newChieftanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newRank.
        /// </summary>
        internal static string param_newRank {
            get {
                return ResourceManager.GetString("param_newRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string param_text {
            get {
                return ResourceManager.GetString("param_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usersToInvite.
        /// </summary>
        internal static string param_usersToInvite {
            get {
                return ResourceManager.GetString("param_usersToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userToInvite.
        /// </summary>
        internal static string param_userToInvite {
            get {
                return ResourceManager.GetString("param_userToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat client.
        /// </summary>
        internal static string ProdCHAT {
            get {
                return ResourceManager.GetString("ProdCHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo II (Retail).
        /// </summary>
        internal static string ProdD2DV {
            get {
                return ResourceManager.GetString("ProdD2DV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo 2: Shareware.
        /// </summary>
        internal static string ProdD2SH {
            get {
                return ResourceManager.GetString("ProdD2SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo II: The Lord of Destruction.
        /// </summary>
        internal static string ProdD2XP {
            get {
                return ResourceManager.GetString("ProdD2XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo Classic (Retail).
        /// </summary>
        internal static string ProdDRTL {
            get {
                return ResourceManager.GetString("ProdDRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diablo Classic (Shareware).
        /// </summary>
        internal static string ProdDSHR {
            get {
                return ResourceManager.GetString("ProdDSHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan Starcraft.
        /// </summary>
        internal static string ProdJSTR {
            get {
                return ResourceManager.GetString("ProdJSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft: Brood War.
        /// </summary>
        internal static string ProdSEXP {
            get {
                return ResourceManager.GetString("ProdSEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft: Shareware.
        /// </summary>
        internal static string ProdSSHR {
            get {
                return ResourceManager.GetString("ProdSSHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starcraft (Retail).
        /// </summary>
        internal static string ProdSTAR {
            get {
                return ResourceManager.GetString("ProdSTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unknown Product or Client.
        /// </summary>
        internal static string ProdUNKN {
            get {
                return ResourceManager.GetString("ProdUNKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft II: Battle.net Edition.
        /// </summary>
        internal static string ProdW2BN {
            get {
                return ResourceManager.GetString("ProdW2BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III: The Frozen Throne.
        /// </summary>
        internal static string ProdW3XP {
            get {
                return ResourceManager.GetString("ProdW3XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcraft III: The Reign of Chaos.
        /// </summary>
        internal static string ProdWAR3 {
            get {
                return ResourceManager.GetString("ProdWAR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net has sent a packet that exceeds the maximum length supported..
        /// </summary>
        internal static string ReceivedTooLongMessage {
            get {
                return ResourceManager.GetString("ReceivedTooLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection was unable to complete a connection to {0}:{1} (&apos;{2}&apos;).  More information is available in the exception..
        /// </summary>
        internal static string UnableToConnectFmt {
            get {
                return ResourceManager.GetString("UnableToConnectFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer was unable to resolve host name &apos;{0}&apos;.  If necessary, add an entry to %SystemRoot%\system32\drivers\etc\hosts, or flush your DNS resolver cache, and try again..
        /// </summary>
        internal static string UnableToResolveHostFmt {
            get {
                return ResourceManager.GetString("UnableToResolveHostFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net has requested that your account be upgraded, but this is not supported.  Please upgrade your account via the official Warcraft III client..
        /// </summary>
        internal static string UpgradeRequestedUnsupported {
            get {
                return ResourceManager.GetString("UpgradeRequestedUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Warcraft 3 server validation check failed.  You may not be connecting to a legitimate Battle.net server..
        /// </summary>
        internal static string War3ServerValidationFailed {
            get {
                return ResourceManager.GetString("War3ServerValidationFailed", resourceCulture);
            }
        }
    }
}
